Repository neil9669/eggStremely, pull requests merged in 2023-05, with the labels that each got.

#50 add rule to condition to fix bug, change grogu spawn position, add ar…
  assets/js/babyYoda.js
  assets/js/eggJar.js
  assets/js/enemy.js
  assets/js/utils/generateRandomPosition.js
Labels: bug

#59 Add collision detection
  assets/js/babyYoda.js
  assets/js/eggJar.js
  assets/js/enemy.js
  assets/js/main.js
  assets/js/scenes.js
Labels: bug, enhancement

#74 Add favicon
  favicon.png
  index.html
Labels: enhancement

#79 add background behind canvas, update page title, add go play again bu…
  assets/js/scenes.js
  assets/style.css
  index.html
  public/starry-sky.webp
Labels: enhancement
